/**
 * Microsoft Azure Blob Storage
 * Fastly will upload log messages to the Azure Blob Storage container in the format specified in the Azure Blob object.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class ModelLoggingAzureblob {
    
    constructor() { 
        
        ModelLoggingAzureblob.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelLoggingAzureblob();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('service_id')) {
                obj['service_id'] = ApiClient.convertToType(data['service_id'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('placement')) {
                obj['placement'] = ApiClient.convertToType(data['placement'], 'String');
            }
            if (data.hasOwnProperty('format_version')) {
                obj['format_version'] = ApiClient.convertToType(data['format_version'], 'Number');
            }
            if (data.hasOwnProperty('response_condition')) {
                obj['response_condition'] = ApiClient.convertToType(data['response_condition'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('message_type')) {
                obj['message_type'] = ApiClient.convertToType(data['message_type'], 'String');
            }
            if (data.hasOwnProperty('timestamp_format')) {
                obj['timestamp_format'] = ApiClient.convertToType(data['timestamp_format'], 'String');
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'Number');
            }
            if (data.hasOwnProperty('gzip_level')) {
                obj['gzip_level'] = ApiClient.convertToType(data['gzip_level'], 'Number');
            }
            if (data.hasOwnProperty('compression_codec')) {
                obj['compression_codec'] = ApiClient.convertToType(data['compression_codec'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('account_name')) {
                obj['account_name'] = ApiClient.convertToType(data['account_name'], 'String');
            }
            if (data.hasOwnProperty('container')) {
                obj['container'] = ApiClient.convertToType(data['container'], 'String');
            }
            if (data.hasOwnProperty('sas_token')) {
                obj['sas_token'] = ApiClient.convertToType(data['sas_token'], 'String');
            }
            if (data.hasOwnProperty('public_key')) {
                obj['public_key'] = ApiClient.convertToType(data['public_key'], 'String');
            }
            if (data.hasOwnProperty('file_max_bytes')) {
                obj['file_max_bytes'] = ApiClient.convertToType(data['file_max_bytes'], 'Number');
            }
        }
        return obj;
    }


}


ModelLoggingAzureblob.prototype['created_at'] = undefined;


ModelLoggingAzureblob.prototype['deleted_at'] = undefined;


ModelLoggingAzureblob.prototype['updated_at'] = undefined;


ModelLoggingAzureblob.prototype['service_id'] = undefined;


ModelLoggingAzureblob.prototype['version'] = undefined;


ModelLoggingAzureblob.prototype['name'] = undefined;


ModelLoggingAzureblob.prototype['placement'] = undefined;


ModelLoggingAzureblob.prototype['format_version'] = FormatVersionEnum.2;


ModelLoggingAzureblob.prototype['response_condition'] = undefined;


ModelLoggingAzureblob.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';


ModelLoggingAzureblob.prototype['message_type'] = 'classic';


ModelLoggingAzureblob.prototype['timestamp_format'] = undefined;


ModelLoggingAzureblob.prototype['period'] = 3600;


ModelLoggingAzureblob.prototype['gzip_level'] = 0;


ModelLoggingAzureblob.prototype['compression_codec'] = undefined;


ModelLoggingAzureblob.prototype['path'] = 'null';


ModelLoggingAzureblob.prototype['account_name'] = undefined;


ModelLoggingAzureblob.prototype['container'] = undefined;


ModelLoggingAzureblob.prototype['sas_token'] = undefined;


ModelLoggingAzureblob.prototype['public_key'] = 'null';


ModelLoggingAzureblob.prototype['file_max_bytes'] = undefined;






ModelLoggingAzureblob['PlacementEnum'] = {

    
    "none": "none",

    
    "waf_debug": "waf_debug",

    
    "null": "null"
};



ModelLoggingAzureblob['FormatVersionEnum'] = {

    
    "1": 1,

    
    "2": 2
};



ModelLoggingAzureblob['MessageTypeEnum'] = {

    
    "classic": "classic",

    
    "loggly": "loggly",

    
    "logplex": "logplex",

    
    "blank": "blank"
};



ModelLoggingAzureblob['CompressionCodecEnum'] = {

    
    "zstd": "zstd",

    
    "snappy": "snappy",

    
    "gzip": "gzip"
};



export default ModelLoggingAzureblob;

