/**
 * User
 * A user of the Fastly API and web interface. A user is always associated with a customer.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RelationshipUserUserData from './RelationshipUserUserData';


class RelationshipUserUser {
    
    constructor() { 
        
        RelationshipUserUser.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RelationshipUserUser();

            if (data.hasOwnProperty('data')) {
                obj['data'] = RelationshipUserUserData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}


RelationshipUserUser.prototype['data'] = undefined;






export default RelationshipUserUser;

