/**
 * User
 * A user of the Fastly API and web interface. A user is always associated with a customer.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

export default class RoleUser {
    
        
        "user" = "user";

    
        
        "billing" = "billing";

    
        
        "engineer" = "engineer";

    
        
        "superuser" = "superuser";

    

    
    static constructFromObject(object) {
        return object;
    }
}

