/**
 * Rate Limiter
 * Rate limiters add configurable origin request rate limiting to a service. Use of this feature is by invite only and subject to the terms set forth in the invitation you were emailed. To create a rate limiting policy, you must have a [paid account with a contract](https://docs.fastly.com/en/guides/accounts-and-pricing-plans#paid-accounts-with-contractual-commitments) for Fastly’s services.
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import InlineObject from './model/InlineObject';
import InlineObject1 from './model/InlineObject1';
import InlineResponse200 from './model/InlineResponse200';
import ModelRateLimiter from './model/ModelRateLimiter';
import ServiceServiceIdVersionVersionIdRateLimitersResponse from './model/ServiceServiceIdVersionVersionIdRateLimitersResponse';
import VclServicesRateLimiterApi from './api/VclServicesRateLimiterApi';



export {
    
    ApiClient,

    
    InlineObject,

    
    InlineObject1,

    
    InlineResponse200,

    
    ModelRateLimiter,

    
    ServiceServiceIdVersionVersionIdRateLimitersResponse,

    
    VclServicesRateLimiterApi
};
