/**
 * Fastly API
 * Via the Fastly API you can perform any of the operations that are possible within the management console,  including creating services, domains, and backends, configuring rules or uploading your own application code, as well as account operations such as user administration and billing reports. The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts. For the most accurate and up-to-date API reference content, visit our [Developer Hub](https://developer.fastly.com/reference/api/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';
import ServiceIdAndVersion from './ServiceIdAndVersion';
import Timestamps from './Timestamps';


class HeaderResponse {
    
    constructor() { 
        Header.initialize(this);ServiceIdAndVersion.initialize(this);Timestamps.initialize(this);
        HeaderResponse.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HeaderResponse();
            Header.constructFromObject(data, obj);
            ServiceIdAndVersion.constructFromObject(data, obj);
            Timestamps.constructFromObject(data, obj);

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('cache_condition')) {
                obj['cache_condition'] = ApiClient.convertToType(data['cache_condition'], 'String');
            }
            if (data.hasOwnProperty('dst')) {
                obj['dst'] = ApiClient.convertToType(data['dst'], 'String');
            }
            if (data.hasOwnProperty('ignore_if_set')) {
                obj['ignore_if_set'] = ApiClient.convertToType(data['ignore_if_set'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('regex')) {
                obj['regex'] = ApiClient.convertToType(data['regex'], 'String');
            }
            if (data.hasOwnProperty('request_condition')) {
                obj['request_condition'] = ApiClient.convertToType(data['request_condition'], 'String');
            }
            if (data.hasOwnProperty('response_condition')) {
                obj['response_condition'] = ApiClient.convertToType(data['response_condition'], 'String');
            }
            if (data.hasOwnProperty('src')) {
                obj['src'] = ApiClient.convertToType(data['src'], 'String');
            }
            if (data.hasOwnProperty('substitution')) {
                obj['substitution'] = ApiClient.convertToType(data['substitution'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('service_id')) {
                obj['service_id'] = ApiClient.convertToType(data['service_id'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }


}


HeaderResponse.prototype['action'] = undefined;


HeaderResponse.prototype['cache_condition'] = undefined;


HeaderResponse.prototype['dst'] = undefined;


HeaderResponse.prototype['ignore_if_set'] = undefined;


HeaderResponse.prototype['name'] = undefined;


HeaderResponse.prototype['priority'] = 100;


HeaderResponse.prototype['regex'] = undefined;


HeaderResponse.prototype['request_condition'] = undefined;


HeaderResponse.prototype['response_condition'] = undefined;


HeaderResponse.prototype['src'] = undefined;


HeaderResponse.prototype['substitution'] = undefined;


HeaderResponse.prototype['type'] = undefined;


HeaderResponse.prototype['service_id'] = undefined;


HeaderResponse.prototype['version'] = undefined;


HeaderResponse.prototype['created_at'] = undefined;


HeaderResponse.prototype['deleted_at'] = undefined;


HeaderResponse.prototype['updated_at'] = undefined;


// Implement Header interface:

Header.prototype['action'] = undefined;

Header.prototype['cache_condition'] = undefined;

Header.prototype['dst'] = undefined;

Header.prototype['ignore_if_set'] = undefined;

Header.prototype['name'] = undefined;

Header.prototype['priority'] = 100;

Header.prototype['regex'] = undefined;

Header.prototype['request_condition'] = undefined;

Header.prototype['response_condition'] = undefined;

Header.prototype['src'] = undefined;

Header.prototype['substitution'] = undefined;

Header.prototype['type'] = undefined;
// Implement ServiceIdAndVersion interface:

ServiceIdAndVersion.prototype['service_id'] = undefined;

ServiceIdAndVersion.prototype['version'] = undefined;
// Implement Timestamps interface:

Timestamps.prototype['created_at'] = undefined;

Timestamps.prototype['deleted_at'] = undefined;

Timestamps.prototype['updated_at'] = undefined;




HeaderResponse['ActionEnum'] = {

    
    "set": "set",

    
    "append": "append",

    
    "delete": "delete",

    
    "regex": "regex",

    
    "regex_repeat": "regex_repeat"
};



HeaderResponse['TypeEnum'] = {

    
    "request": "request",

    
    "fetch": "fetch",

    
    "cache": "cache",

    
    "response": "response"
};



export default HeaderResponse;

