/**
 * Fastly API
 * Via the Fastly API you can perform any of the operations that are possible within the management console,  including creating services, domains, and backends, configuring rules or uploading your own application code, as well as account operations such as user administration and billing reports. The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts. For the most accurate and up-to-date API reference content, visit our [Developer Hub](https://developer.fastly.com/reference/api/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoggingAddressAndPort from './LoggingAddressAndPort';
import LoggingCommon from './LoggingCommon';
import LoggingCompressionCodec from './LoggingCompressionCodec';
import LoggingFormatVersion from './LoggingFormatVersion';
import LoggingGenericCommon from './LoggingGenericCommon';
import LoggingMessageType from './LoggingMessageType';
import LoggingPlacement from './LoggingPlacement';
import LoggingSftpAllOf from './LoggingSftpAllOf';


class LoggingSftp {
    
    constructor() { 
        LoggingCommon.initialize(this);LoggingGenericCommon.initialize(this);LoggingAddressAndPort.initialize(this);LoggingSftpAllOf.initialize(this);
        LoggingSftp.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoggingSftp();
            LoggingCommon.constructFromObject(data, obj);
            LoggingGenericCommon.constructFromObject(data, obj);
            LoggingAddressAndPort.constructFromObject(data, obj);
            LoggingSftpAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('placement')) {
                obj['placement'] = LoggingPlacement.constructFromObject(data['placement']);
            }
            if (data.hasOwnProperty('format_version')) {
                obj['format_version'] = LoggingFormatVersion.constructFromObject(data['format_version']);
            }
            if (data.hasOwnProperty('response_condition')) {
                obj['response_condition'] = ApiClient.convertToType(data['response_condition'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('message_type')) {
                obj['message_type'] = LoggingMessageType.constructFromObject(data['message_type']);
            }
            if (data.hasOwnProperty('timestamp_format')) {
                obj['timestamp_format'] = ApiClient.convertToType(data['timestamp_format'], 'String');
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'Number');
            }
            if (data.hasOwnProperty('gzip_level')) {
                obj['gzip_level'] = ApiClient.convertToType(data['gzip_level'], 'Number');
            }
            if (data.hasOwnProperty('compression_codec')) {
                obj['compression_codec'] = LoggingCompressionCodec.constructFromObject(data['compression_codec']);
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], Object);
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('public_key')) {
                obj['public_key'] = ApiClient.convertToType(data['public_key'], 'String');
            }
            if (data.hasOwnProperty('secret_key')) {
                obj['secret_key'] = ApiClient.convertToType(data['secret_key'], 'String');
            }
            if (data.hasOwnProperty('ssh_known_hosts')) {
                obj['ssh_known_hosts'] = ApiClient.convertToType(data['ssh_known_hosts'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
        }
        return obj;
    }


}


LoggingSftp.prototype['name'] = undefined;


LoggingSftp.prototype['placement'] = undefined;


LoggingSftp.prototype['format_version'] = undefined;


LoggingSftp.prototype['response_condition'] = undefined;


LoggingSftp.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';


LoggingSftp.prototype['message_type'] = undefined;


LoggingSftp.prototype['timestamp_format'] = undefined;


LoggingSftp.prototype['period'] = 3600;


LoggingSftp.prototype['gzip_level'] = 0;


LoggingSftp.prototype['compression_codec'] = undefined;


LoggingSftp.prototype['address'] = undefined;


LoggingSftp.prototype['port'] = undefined;


LoggingSftp.prototype['password'] = undefined;


LoggingSftp.prototype['path'] = 'null';


LoggingSftp.prototype['public_key'] = 'null';


LoggingSftp.prototype['secret_key'] = 'null';


LoggingSftp.prototype['ssh_known_hosts'] = undefined;


LoggingSftp.prototype['user'] = undefined;


// Implement LoggingCommon interface:

LoggingCommon.prototype['name'] = undefined;

LoggingCommon.prototype['placement'] = undefined;

LoggingCommon.prototype['format_version'] = undefined;

LoggingCommon.prototype['response_condition'] = undefined;

LoggingCommon.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';
// Implement LoggingGenericCommon interface:

LoggingGenericCommon.prototype['message_type'] = undefined;

LoggingGenericCommon.prototype['timestamp_format'] = undefined;

LoggingGenericCommon.prototype['period'] = 3600;

LoggingGenericCommon.prototype['gzip_level'] = 0;

LoggingGenericCommon.prototype['compression_codec'] = undefined;
// Implement LoggingAddressAndPort interface:

LoggingAddressAndPort.prototype['address'] = undefined;

LoggingAddressAndPort.prototype['port'] = 514;
// Implement LoggingSftpAllOf interface:

LoggingSftpAllOf.prototype['password'] = undefined;

LoggingSftpAllOf.prototype['path'] = 'null';

LoggingSftpAllOf.prototype['port'] = undefined;

LoggingSftpAllOf.prototype['public_key'] = 'null';

LoggingSftpAllOf.prototype['secret_key'] = 'null';

LoggingSftpAllOf.prototype['ssh_known_hosts'] = undefined;

LoggingSftpAllOf.prototype['user'] = undefined;




export default LoggingSftp;

