/**
 * Fastly API
 * Via the Fastly API you can perform any of the operations that are possible within the management console,  including creating services, domains, and backends, configuring rules or uploading your own application code, as well as account operations such as user administration and billing reports. The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts. For the most accurate and up-to-date API reference content, visit our [Developer Hub](https://developer.fastly.com/reference/api/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoggingCommon from './LoggingCommon';
import LoggingCompressionCodec from './LoggingCompressionCodec';
import LoggingFormatVersion from './LoggingFormatVersion';
import LoggingFtpAllOf from './LoggingFtpAllOf';
import LoggingGenericCommon from './LoggingGenericCommon';
import LoggingMessageType from './LoggingMessageType';
import LoggingPlacement from './LoggingPlacement';


class LoggingFtp {
    
    constructor() { 
        LoggingCommon.initialize(this);LoggingGenericCommon.initialize(this);LoggingFtpAllOf.initialize(this);
        LoggingFtp.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoggingFtp();
            LoggingCommon.constructFromObject(data, obj);
            LoggingGenericCommon.constructFromObject(data, obj);
            LoggingFtpAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('placement')) {
                obj['placement'] = LoggingPlacement.constructFromObject(data['placement']);
            }
            if (data.hasOwnProperty('format_version')) {
                obj['format_version'] = LoggingFormatVersion.constructFromObject(data['format_version']);
            }
            if (data.hasOwnProperty('response_condition')) {
                obj['response_condition'] = ApiClient.convertToType(data['response_condition'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('message_type')) {
                obj['message_type'] = LoggingMessageType.constructFromObject(data['message_type']);
            }
            if (data.hasOwnProperty('timestamp_format')) {
                obj['timestamp_format'] = ApiClient.convertToType(data['timestamp_format'], 'String');
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'Number');
            }
            if (data.hasOwnProperty('gzip_level')) {
                obj['gzip_level'] = ApiClient.convertToType(data['gzip_level'], 'Number');
            }
            if (data.hasOwnProperty('compression_codec')) {
                obj['compression_codec'] = LoggingCompressionCodec.constructFromObject(data['compression_codec']);
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('hostname')) {
                obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
            }
            if (data.hasOwnProperty('ipv4')) {
                obj['ipv4'] = ApiClient.convertToType(data['ipv4'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
            if (data.hasOwnProperty('public_key')) {
                obj['public_key'] = ApiClient.convertToType(data['public_key'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
        }
        return obj;
    }


}


LoggingFtp.prototype['name'] = undefined;


LoggingFtp.prototype['placement'] = undefined;


LoggingFtp.prototype['format_version'] = undefined;


LoggingFtp.prototype['response_condition'] = undefined;


LoggingFtp.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';


LoggingFtp.prototype['message_type'] = undefined;


LoggingFtp.prototype['timestamp_format'] = undefined;


LoggingFtp.prototype['period'] = 3600;


LoggingFtp.prototype['gzip_level'] = 0;


LoggingFtp.prototype['compression_codec'] = undefined;


LoggingFtp.prototype['address'] = undefined;


LoggingFtp.prototype['hostname'] = undefined;


LoggingFtp.prototype['ipv4'] = undefined;


LoggingFtp.prototype['password'] = undefined;


LoggingFtp.prototype['path'] = undefined;


LoggingFtp.prototype['port'] = 21;


LoggingFtp.prototype['public_key'] = 'null';


LoggingFtp.prototype['user'] = undefined;


// Implement LoggingCommon interface:

LoggingCommon.prototype['name'] = undefined;

LoggingCommon.prototype['placement'] = undefined;

LoggingCommon.prototype['format_version'] = undefined;

LoggingCommon.prototype['response_condition'] = undefined;

LoggingCommon.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';
// Implement LoggingGenericCommon interface:

LoggingGenericCommon.prototype['message_type'] = undefined;

LoggingGenericCommon.prototype['timestamp_format'] = undefined;

LoggingGenericCommon.prototype['period'] = 3600;

LoggingGenericCommon.prototype['gzip_level'] = 0;

LoggingGenericCommon.prototype['compression_codec'] = undefined;
// Implement LoggingFtpAllOf interface:

LoggingFtpAllOf.prototype['address'] = undefined;

LoggingFtpAllOf.prototype['hostname'] = undefined;

LoggingFtpAllOf.prototype['ipv4'] = undefined;

LoggingFtpAllOf.prototype['password'] = undefined;

LoggingFtpAllOf.prototype['path'] = undefined;

LoggingFtpAllOf.prototype['port'] = 21;

LoggingFtpAllOf.prototype['public_key'] = 'null';

LoggingFtpAllOf.prototype['user'] = undefined;




export default LoggingFtp;

