/**
 * Fastly API
 * Via the Fastly API you can perform any of the operations that are possible within the management console,  including creating services, domains, and backends, configuring rules or uploading your own application code, as well as account operations such as user administration and billing reports. The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts. For the most accurate and up-to-date API reference content, visit our [Developer Hub](https://developer.fastly.com/reference/api/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoggingCommon from './LoggingCommon';
import LoggingFormatVersion from './LoggingFormatVersion';
import LoggingLogentriesAllOf from './LoggingLogentriesAllOf';
import LoggingPlacement from './LoggingPlacement';
import LoggingUseTls from './LoggingUseTls';


class LoggingLogentries {
    
    constructor() { 
        LoggingCommon.initialize(this);LoggingLogentriesAllOf.initialize(this);
        LoggingLogentries.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoggingLogentries();
            LoggingCommon.constructFromObject(data, obj);
            LoggingLogentriesAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('placement')) {
                obj['placement'] = LoggingPlacement.constructFromObject(data['placement']);
            }
            if (data.hasOwnProperty('format_version')) {
                obj['format_version'] = LoggingFormatVersion.constructFromObject(data['format_version']);
            }
            if (data.hasOwnProperty('response_condition')) {
                obj['response_condition'] = ApiClient.convertToType(data['response_condition'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('use_tls')) {
                obj['use_tls'] = LoggingUseTls.constructFromObject(data['use_tls']);
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
        }
        return obj;
    }


}


LoggingLogentries.prototype['name'] = undefined;


LoggingLogentries.prototype['placement'] = undefined;


LoggingLogentries.prototype['format_version'] = undefined;


LoggingLogentries.prototype['response_condition'] = undefined;


LoggingLogentries.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';


LoggingLogentries.prototype['port'] = 20000;


LoggingLogentries.prototype['token'] = undefined;


LoggingLogentries.prototype['use_tls'] = undefined;


LoggingLogentries.prototype['region'] = undefined;


// Implement LoggingCommon interface:

LoggingCommon.prototype['name'] = undefined;

LoggingCommon.prototype['placement'] = undefined;

LoggingCommon.prototype['format_version'] = undefined;

LoggingCommon.prototype['response_condition'] = undefined;

LoggingCommon.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';
// Implement LoggingLogentriesAllOf interface:

LoggingLogentriesAllOf.prototype['port'] = 20000;

LoggingLogentriesAllOf.prototype['token'] = undefined;

LoggingLogentriesAllOf.prototype['use_tls'] = undefined;

LoggingLogentriesAllOf.prototype['region'] = undefined;




LoggingLogentries['RegionEnum'] = {

    
    "US": "US",

    
    "US-2": "US-2",

    
    "US-3": "US-3",

    
    "EU": "EU",

    
    "CA": "CA",

    
    "AU": "AU",

    
    "AP": "AP"
};



export default LoggingLogentries;

