/**
 * Fastly API
 * Via the Fastly API you can perform any of the operations that are possible within the management console,  including creating services, domains, and backends, configuring rules or uploading your own application code, as well as account operations such as user administration and billing reports. The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts. For the most accurate and up-to-date API reference content, visit our [Developer Hub](https://developer.fastly.com/reference/api/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoggingAddressAndPort from './LoggingAddressAndPort';
import LoggingCommon from './LoggingCommon';
import LoggingFormatVersion from './LoggingFormatVersion';
import LoggingMessageType from './LoggingMessageType';
import LoggingPlacement from './LoggingPlacement';
import LoggingSyslogAllOf from './LoggingSyslogAllOf';
import LoggingTlsCommon from './LoggingTlsCommon';
import LoggingUseTls from './LoggingUseTls';


class LoggingSyslog {
    
    constructor() { 
        LoggingCommon.initialize(this);LoggingTlsCommon.initialize(this);LoggingAddressAndPort.initialize(this);LoggingSyslogAllOf.initialize(this);
        LoggingSyslog.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoggingSyslog();
            LoggingCommon.constructFromObject(data, obj);
            LoggingTlsCommon.constructFromObject(data, obj);
            LoggingAddressAndPort.constructFromObject(data, obj);
            LoggingSyslogAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('placement')) {
                obj['placement'] = LoggingPlacement.constructFromObject(data['placement']);
            }
            if (data.hasOwnProperty('format_version')) {
                obj['format_version'] = LoggingFormatVersion.constructFromObject(data['format_version']);
            }
            if (data.hasOwnProperty('response_condition')) {
                obj['response_condition'] = ApiClient.convertToType(data['response_condition'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('tls_ca_cert')) {
                obj['tls_ca_cert'] = ApiClient.convertToType(data['tls_ca_cert'], 'String');
            }
            if (data.hasOwnProperty('tls_client_cert')) {
                obj['tls_client_cert'] = ApiClient.convertToType(data['tls_client_cert'], 'String');
            }
            if (data.hasOwnProperty('tls_client_key')) {
                obj['tls_client_key'] = ApiClient.convertToType(data['tls_client_key'], 'String');
            }
            if (data.hasOwnProperty('tls_hostname')) {
                obj['tls_hostname'] = ApiClient.convertToType(data['tls_hostname'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
            if (data.hasOwnProperty('message_type')) {
                obj['message_type'] = LoggingMessageType.constructFromObject(data['message_type']);
            }
            if (data.hasOwnProperty('hostname')) {
                obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
            }
            if (data.hasOwnProperty('ipv4')) {
                obj['ipv4'] = ApiClient.convertToType(data['ipv4'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('use_tls')) {
                obj['use_tls'] = LoggingUseTls.constructFromObject(data['use_tls']);
            }
        }
        return obj;
    }


}


LoggingSyslog.prototype['name'] = undefined;


LoggingSyslog.prototype['placement'] = undefined;


LoggingSyslog.prototype['format_version'] = undefined;


LoggingSyslog.prototype['response_condition'] = undefined;


LoggingSyslog.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';


LoggingSyslog.prototype['tls_ca_cert'] = 'null';


LoggingSyslog.prototype['tls_client_cert'] = 'null';


LoggingSyslog.prototype['tls_client_key'] = 'null';


LoggingSyslog.prototype['tls_hostname'] = 'null';


LoggingSyslog.prototype['address'] = undefined;


LoggingSyslog.prototype['port'] = 514;


LoggingSyslog.prototype['message_type'] = undefined;


LoggingSyslog.prototype['hostname'] = undefined;


LoggingSyslog.prototype['ipv4'] = undefined;


LoggingSyslog.prototype['token'] = 'null';


LoggingSyslog.prototype['use_tls'] = undefined;


// Implement LoggingCommon interface:

LoggingCommon.prototype['name'] = undefined;

LoggingCommon.prototype['placement'] = undefined;

LoggingCommon.prototype['format_version'] = undefined;

LoggingCommon.prototype['response_condition'] = undefined;

LoggingCommon.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';
// Implement LoggingTlsCommon interface:

LoggingTlsCommon.prototype['tls_ca_cert'] = 'null';

LoggingTlsCommon.prototype['tls_client_cert'] = 'null';

LoggingTlsCommon.prototype['tls_client_key'] = 'null';

LoggingTlsCommon.prototype['tls_hostname'] = 'null';
// Implement LoggingAddressAndPort interface:

LoggingAddressAndPort.prototype['address'] = undefined;

LoggingAddressAndPort.prototype['port'] = 514;
// Implement LoggingSyslogAllOf interface:

LoggingSyslogAllOf.prototype['message_type'] = undefined;

LoggingSyslogAllOf.prototype['hostname'] = undefined;

LoggingSyslogAllOf.prototype['ipv4'] = undefined;

LoggingSyslogAllOf.prototype['token'] = 'null';

LoggingSyslogAllOf.prototype['use_tls'] = undefined;




export default LoggingSyslog;

