/**
 * Fastly API
 * Via the Fastly API you can perform any of the operations that are possible within the management console,  including creating services, domains, and backends, configuring rules or uploading your own application code, as well as account operations such as user administration and billing reports. The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts. For the most accurate and up-to-date API reference content, visit our [Developer Hub](https://developer.fastly.com/reference/api/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoggingCommon from './LoggingCommon';
import LoggingFormatVersion from './LoggingFormatVersion';
import LoggingGcsCommon from './LoggingGcsCommon';
import LoggingGooglePubsubAllOf from './LoggingGooglePubsubAllOf';
import LoggingPlacement from './LoggingPlacement';


class LoggingGooglePubsub {
    
    constructor() { 
        LoggingCommon.initialize(this);LoggingGcsCommon.initialize(this);LoggingGooglePubsubAllOf.initialize(this);
        LoggingGooglePubsub.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoggingGooglePubsub();
            LoggingCommon.constructFromObject(data, obj);
            LoggingGcsCommon.constructFromObject(data, obj);
            LoggingGooglePubsubAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('placement')) {
                obj['placement'] = LoggingPlacement.constructFromObject(data['placement']);
            }
            if (data.hasOwnProperty('format_version')) {
                obj['format_version'] = LoggingFormatVersion.constructFromObject(data['format_version']);
            }
            if (data.hasOwnProperty('response_condition')) {
                obj['response_condition'] = ApiClient.convertToType(data['response_condition'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
            if (data.hasOwnProperty('secret_key')) {
                obj['secret_key'] = ApiClient.convertToType(data['secret_key'], 'String');
            }
            if (data.hasOwnProperty('topic')) {
                obj['topic'] = ApiClient.convertToType(data['topic'], 'String');
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'String');
            }
        }
        return obj;
    }


}


LoggingGooglePubsub.prototype['name'] = undefined;


LoggingGooglePubsub.prototype['placement'] = undefined;


LoggingGooglePubsub.prototype['format_version'] = undefined;


LoggingGooglePubsub.prototype['response_condition'] = undefined;


LoggingGooglePubsub.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';


LoggingGooglePubsub.prototype['user'] = undefined;


LoggingGooglePubsub.prototype['secret_key'] = undefined;


LoggingGooglePubsub.prototype['topic'] = undefined;


LoggingGooglePubsub.prototype['project_id'] = undefined;


// Implement LoggingCommon interface:

LoggingCommon.prototype['name'] = undefined;

LoggingCommon.prototype['placement'] = undefined;

LoggingCommon.prototype['format_version'] = undefined;

LoggingCommon.prototype['response_condition'] = undefined;

LoggingCommon.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';
// Implement LoggingGcsCommon interface:

LoggingGcsCommon.prototype['user'] = undefined;

LoggingGcsCommon.prototype['secret_key'] = undefined;
// Implement LoggingGooglePubsubAllOf interface:

LoggingGooglePubsubAllOf.prototype['topic'] = undefined;

LoggingGooglePubsubAllOf.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';

LoggingGooglePubsubAllOf.prototype['project_id'] = undefined;




export default LoggingGooglePubsub;

