/**
 * Fastly API
 * Via the Fastly API you can perform any of the operations that are possible within the management console,  including creating services, domains, and backends, configuring rules or uploading your own application code, as well as account operations such as user administration and billing reports. The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts. For the most accurate and up-to-date API reference content, visit our [Developer Hub](https://developer.fastly.com/reference/api/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoggingFormatVersion from './LoggingFormatVersion';
import LoggingHttps from './LoggingHttps';
import LoggingMessageType from './LoggingMessageType';
import LoggingPlacement from './LoggingPlacement';
import ServiceIdAndVersion from './ServiceIdAndVersion';
import Timestamps from './Timestamps';


class LoggingHttpsResponse {
    
    constructor() { 
        LoggingHttps.initialize(this);Timestamps.initialize(this);ServiceIdAndVersion.initialize(this);
        LoggingHttpsResponse.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoggingHttpsResponse();
            LoggingHttps.constructFromObject(data, obj);
            Timestamps.constructFromObject(data, obj);
            ServiceIdAndVersion.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('placement')) {
                obj['placement'] = LoggingPlacement.constructFromObject(data['placement']);
            }
            if (data.hasOwnProperty('format_version')) {
                obj['format_version'] = LoggingFormatVersion.constructFromObject(data['format_version']);
            }
            if (data.hasOwnProperty('response_condition')) {
                obj['response_condition'] = ApiClient.convertToType(data['response_condition'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('tls_ca_cert')) {
                obj['tls_ca_cert'] = ApiClient.convertToType(data['tls_ca_cert'], 'String');
            }
            if (data.hasOwnProperty('tls_client_cert')) {
                obj['tls_client_cert'] = ApiClient.convertToType(data['tls_client_cert'], 'String');
            }
            if (data.hasOwnProperty('tls_client_key')) {
                obj['tls_client_key'] = ApiClient.convertToType(data['tls_client_key'], 'String');
            }
            if (data.hasOwnProperty('tls_hostname')) {
                obj['tls_hostname'] = ApiClient.convertToType(data['tls_hostname'], 'String');
            }
            if (data.hasOwnProperty('request_max_entries')) {
                obj['request_max_entries'] = ApiClient.convertToType(data['request_max_entries'], 'Number');
            }
            if (data.hasOwnProperty('request_max_bytes')) {
                obj['request_max_bytes'] = ApiClient.convertToType(data['request_max_bytes'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
            if (data.hasOwnProperty('header_name')) {
                obj['header_name'] = ApiClient.convertToType(data['header_name'], 'String');
            }
            if (data.hasOwnProperty('message_type')) {
                obj['message_type'] = LoggingMessageType.constructFromObject(data['message_type']);
            }
            if (data.hasOwnProperty('header_value')) {
                obj['header_value'] = ApiClient.convertToType(data['header_value'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('json_format')) {
                obj['json_format'] = ApiClient.convertToType(data['json_format'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('service_id')) {
                obj['service_id'] = ApiClient.convertToType(data['service_id'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
        }
        return obj;
    }


}


LoggingHttpsResponse.prototype['name'] = undefined;


LoggingHttpsResponse.prototype['placement'] = undefined;


LoggingHttpsResponse.prototype['format_version'] = undefined;


LoggingHttpsResponse.prototype['response_condition'] = undefined;


LoggingHttpsResponse.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';


LoggingHttpsResponse.prototype['tls_ca_cert'] = 'null';


LoggingHttpsResponse.prototype['tls_client_cert'] = 'null';


LoggingHttpsResponse.prototype['tls_client_key'] = 'null';


LoggingHttpsResponse.prototype['tls_hostname'] = 'null';


LoggingHttpsResponse.prototype['request_max_entries'] = 0;


LoggingHttpsResponse.prototype['request_max_bytes'] = 0;


LoggingHttpsResponse.prototype['url'] = undefined;


LoggingHttpsResponse.prototype['content_type'] = 'null';


LoggingHttpsResponse.prototype['header_name'] = 'null';


LoggingHttpsResponse.prototype['message_type'] = undefined;


LoggingHttpsResponse.prototype['header_value'] = 'null';


LoggingHttpsResponse.prototype['method'] = 'POST';


LoggingHttpsResponse.prototype['json_format'] = undefined;


LoggingHttpsResponse.prototype['created_at'] = undefined;


LoggingHttpsResponse.prototype['deleted_at'] = undefined;


LoggingHttpsResponse.prototype['updated_at'] = undefined;


LoggingHttpsResponse.prototype['service_id'] = undefined;


LoggingHttpsResponse.prototype['version'] = undefined;


// Implement LoggingHttps interface:

LoggingHttps.prototype['name'] = undefined;

LoggingHttps.prototype['placement'] = undefined;

LoggingHttps.prototype['format_version'] = undefined;

LoggingHttps.prototype['response_condition'] = undefined;

LoggingHttps.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';

LoggingHttps.prototype['tls_ca_cert'] = 'null';

LoggingHttps.prototype['tls_client_cert'] = 'null';

LoggingHttps.prototype['tls_client_key'] = 'null';

LoggingHttps.prototype['tls_hostname'] = 'null';

LoggingHttps.prototype['request_max_entries'] = 0;

LoggingHttps.prototype['request_max_bytes'] = 0;

LoggingHttps.prototype['url'] = undefined;

LoggingHttps.prototype['content_type'] = 'null';

LoggingHttps.prototype['header_name'] = 'null';

LoggingHttps.prototype['message_type'] = undefined;

LoggingHttps.prototype['header_value'] = 'null';

LoggingHttps.prototype['method'] = 'POST';

LoggingHttps.prototype['json_format'] = undefined;
// Implement Timestamps interface:

Timestamps.prototype['created_at'] = undefined;

Timestamps.prototype['deleted_at'] = undefined;

Timestamps.prototype['updated_at'] = undefined;
// Implement ServiceIdAndVersion interface:

ServiceIdAndVersion.prototype['service_id'] = undefined;

ServiceIdAndVersion.prototype['version'] = undefined;




LoggingHttpsResponse['MethodEnum'] = {

    
    "POST": "POST",

    
    "PUT": "PUT"
};



LoggingHttpsResponse['JsonFormatEnum'] = {

    
    "disabled": "0",

    
    "json_array": "1",

    
    "newline_delimited_json": "2"
};



export default LoggingHttpsResponse;

