/**
 * Fastly API
 * Via the Fastly API you can perform any of the operations that are possible within the management console,  including creating services, domains, and backends, configuring rules or uploading your own application code, as well as account operations such as user administration and billing reports. The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts. For the most accurate and up-to-date API reference content, visit developer.fastly.com/reference/api/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoggingUseTls from './LoggingUseTls';


class ModelLoggingKafkaAllOf {
    
    constructor() { 
        
        ModelLoggingKafkaAllOf.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelLoggingKafkaAllOf();

            if (data.hasOwnProperty('topic')) {
                obj['topic'] = ApiClient.convertToType(data['topic'], 'String');
            }
            if (data.hasOwnProperty('brokers')) {
                obj['brokers'] = ApiClient.convertToType(data['brokers'], 'String');
            }
            if (data.hasOwnProperty('compression_codec')) {
                obj['compression_codec'] = ApiClient.convertToType(data['compression_codec'], 'String');
            }
            if (data.hasOwnProperty('required_acks')) {
                obj['required_acks'] = ApiClient.convertToType(data['required_acks'], 'Number');
            }
            if (data.hasOwnProperty('request_max_bytes')) {
                obj['request_max_bytes'] = ApiClient.convertToType(data['request_max_bytes'], 'Number');
            }
            if (data.hasOwnProperty('parse_log_keyvals')) {
                obj['parse_log_keyvals'] = ApiClient.convertToType(data['parse_log_keyvals'], 'Boolean');
            }
            if (data.hasOwnProperty('auth_method')) {
                obj['auth_method'] = ApiClient.convertToType(data['auth_method'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('use_tls')) {
                obj['use_tls'] = LoggingUseTls.constructFromObject(data['use_tls']);
            }
        }
        return obj;
    }


}


ModelLoggingKafkaAllOf.prototype['topic'] = undefined;


ModelLoggingKafkaAllOf.prototype['brokers'] = undefined;


ModelLoggingKafkaAllOf.prototype['compression_codec'] = undefined;


ModelLoggingKafkaAllOf.prototype['required_acks'] = RequiredAcksEnum.1;


ModelLoggingKafkaAllOf.prototype['request_max_bytes'] = 0;


ModelLoggingKafkaAllOf.prototype['parse_log_keyvals'] = undefined;


ModelLoggingKafkaAllOf.prototype['auth_method'] = undefined;


ModelLoggingKafkaAllOf.prototype['user'] = undefined;


ModelLoggingKafkaAllOf.prototype['password'] = undefined;


ModelLoggingKafkaAllOf.prototype['use_tls'] = undefined;






ModelLoggingKafkaAllOf['CompressionCodecEnum'] = {

    
    "gzip": "gzip",

    
    "snappy": "snappy",

    
    "lz4": "lz4",

    
    "null": "null"
};



ModelLoggingKafkaAllOf['RequiredAcksEnum'] = {

    
    "1": 1,

    
    "0": 0,

    
    "-1": -1
};



ModelLoggingKafkaAllOf['AuthMethodEnum'] = {

    
    "plain": "plain",

    
    "scram-sha-256": "scram-sha-256",

    
    "scram-sha-512": "scram-sha-512"
};



export default ModelLoggingKafkaAllOf;

