/**
 * Fastly API
 * Via the Fastly API you can perform any of the operations that are possible within the management console,  including creating services, domains, and backends, configuring rules or uploading your own application code, as well as account operations such as user administration and billing reports. The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts. For the most accurate and up-to-date API reference content, visit our [Developer Hub](https://developer.fastly.com/reference/api/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Data from './Data';
import Pagination from './Pagination';
import PaginationLinks from './PaginationLinks';
import PaginationMeta from './PaginationMeta';
import TlsBulkCertificatesResponseAllOf from './TlsBulkCertificatesResponseAllOf';


class TlsBulkCertificatesResponse {
    
    constructor() { 
        Pagination.initialize(this);TlsBulkCertificatesResponseAllOf.initialize(this);
        TlsBulkCertificatesResponse.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TlsBulkCertificatesResponse();
            Pagination.constructFromObject(data, obj);
            TlsBulkCertificatesResponseAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('links')) {
                obj['links'] = PaginationLinks.constructFromObject(data['links']);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = PaginationMeta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Data]);
            }
        }
        return obj;
    }


}


TlsBulkCertificatesResponse.prototype['links'] = undefined;


TlsBulkCertificatesResponse.prototype['meta'] = undefined;


TlsBulkCertificatesResponse.prototype['data'] = undefined;


// Implement Pagination interface:

Pagination.prototype['links'] = undefined;

Pagination.prototype['meta'] = undefined;
// Implement TlsBulkCertificatesResponseAllOf interface:

TlsBulkCertificatesResponseAllOf.prototype['data'] = undefined;




export default TlsBulkCertificatesResponse;

