/**
 * VCL Diff
 * Compare the changes in generated VCL between two versions of a service. This is sometimes called a \"diff\" because the comparison may highlight \"differences\" between the versions. To compare the configuration changes between two versions of a service represented in YAML format instead, use the related [diff](/reference/api/utils/diff/#diff-service-versions) endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class ModelVclDiff {
    
    constructor() { 
        
        ModelVclDiff.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelVclDiff();

            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'Number');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'Number');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('diff')) {
                obj['diff'] = ApiClient.convertToType(data['diff'], 'String');
            }
        }
        return obj;
    }


}


ModelVclDiff.prototype['from'] = undefined;


ModelVclDiff.prototype['to'] = undefined;


ModelVclDiff.prototype['format'] = undefined;


ModelVclDiff.prototype['diff'] = undefined;






export default ModelVclDiff;

