/**
 * Log Shuttle
 * Fastly will upload log messages to the Log Shuttle bucket in the format specified in the logshuttle object.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineObject from '../model/InlineObject';
import InlineObject1 from '../model/InlineObject1';
import InlineResponse200 from '../model/InlineResponse200';


export default class LoggingLogshuttleApi {

    
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    createLogLogshuttleWithHttpInfo(serviceId, versionId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'serviceId' is set
      if (serviceId === undefined || serviceId === null) {
        throw new Error("Missing the required parameter 'serviceId' when calling createLogLogshuttle");
      }
      // verify the required parameter 'versionId' is set
      if (versionId === undefined || versionId === null) {
        throw new Error("Missing the required parameter 'versionId' when calling createLogLogshuttle");
      }

      let pathParams = {
        'service_id': serviceId,
        'version_id': versionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'created_at': opts['createdAt'],
        'deleted_at': opts['deletedAt'],
        'updated_at': opts['updatedAt'],
        'service_id': opts['serviceId2'],
        'version': opts['version'],
        'name': opts['name'],
        'placement': opts['placement'],
        'format_version': opts['formatVersion'],
        'response_condition': opts['responseCondition'],
        'format': opts['format'],
        'token': opts['token'],
        'url': opts['url']
      };

      let authNames = ['token_engineer'];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = InlineObject;
      return this.apiClient.callApi(
        '/service/{service_id}/version/{version_id}/logging/logshuttle', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    createLogLogshuttle(serviceId, versionId, opts) {
      return this.createLogLogshuttleWithHttpInfo(serviceId, versionId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    deleteLogLogshuttleWithHttpInfo(serviceId, versionId, loggingLogshuttleName) {
      let postBody = null;
      // verify the required parameter 'serviceId' is set
      if (serviceId === undefined || serviceId === null) {
        throw new Error("Missing the required parameter 'serviceId' when calling deleteLogLogshuttle");
      }
      // verify the required parameter 'versionId' is set
      if (versionId === undefined || versionId === null) {
        throw new Error("Missing the required parameter 'versionId' when calling deleteLogLogshuttle");
      }
      // verify the required parameter 'loggingLogshuttleName' is set
      if (loggingLogshuttleName === undefined || loggingLogshuttleName === null) {
        throw new Error("Missing the required parameter 'loggingLogshuttleName' when calling deleteLogLogshuttle");
      }

      let pathParams = {
        'service_id': serviceId,
        'version_id': versionId,
        'logging_logshuttle_name': loggingLogshuttleName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token_engineer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/service/{service_id}/version/{version_id}/logging/logshuttle/{logging_logshuttle_name}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    deleteLogLogshuttle(serviceId, versionId, loggingLogshuttleName) {
      return this.deleteLogLogshuttleWithHttpInfo(serviceId, versionId, loggingLogshuttleName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    getLogLogshuttleWithHttpInfo(serviceId, versionId, loggingLogshuttleName) {
      let postBody = null;
      // verify the required parameter 'serviceId' is set
      if (serviceId === undefined || serviceId === null) {
        throw new Error("Missing the required parameter 'serviceId' when calling getLogLogshuttle");
      }
      // verify the required parameter 'versionId' is set
      if (versionId === undefined || versionId === null) {
        throw new Error("Missing the required parameter 'versionId' when calling getLogLogshuttle");
      }
      // verify the required parameter 'loggingLogshuttleName' is set
      if (loggingLogshuttleName === undefined || loggingLogshuttleName === null) {
        throw new Error("Missing the required parameter 'loggingLogshuttleName' when calling getLogLogshuttle");
      }

      let pathParams = {
        'service_id': serviceId,
        'version_id': versionId,
        'logging_logshuttle_name': loggingLogshuttleName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token_engineer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineObject;
      return this.apiClient.callApi(
        '/service/{service_id}/version/{version_id}/logging/logshuttle/{logging_logshuttle_name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    getLogLogshuttle(serviceId, versionId, loggingLogshuttleName) {
      return this.getLogLogshuttleWithHttpInfo(serviceId, versionId, loggingLogshuttleName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    listLogLogshuttleWithHttpInfo(serviceId, versionId) {
      let postBody = null;
      // verify the required parameter 'serviceId' is set
      if (serviceId === undefined || serviceId === null) {
        throw new Error("Missing the required parameter 'serviceId' when calling listLogLogshuttle");
      }
      // verify the required parameter 'versionId' is set
      if (versionId === undefined || versionId === null) {
        throw new Error("Missing the required parameter 'versionId' when calling listLogLogshuttle");
      }

      let pathParams = {
        'service_id': serviceId,
        'version_id': versionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token_engineer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [InlineResponse200];
      return this.apiClient.callApi(
        '/service/{service_id}/version/{version_id}/logging/logshuttle', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    listLogLogshuttle(serviceId, versionId) {
      return this.listLogLogshuttleWithHttpInfo(serviceId, versionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    updateLogLogshuttleWithHttpInfo(serviceId, versionId, loggingLogshuttleName, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'serviceId' is set
      if (serviceId === undefined || serviceId === null) {
        throw new Error("Missing the required parameter 'serviceId' when calling updateLogLogshuttle");
      }
      // verify the required parameter 'versionId' is set
      if (versionId === undefined || versionId === null) {
        throw new Error("Missing the required parameter 'versionId' when calling updateLogLogshuttle");
      }
      // verify the required parameter 'loggingLogshuttleName' is set
      if (loggingLogshuttleName === undefined || loggingLogshuttleName === null) {
        throw new Error("Missing the required parameter 'loggingLogshuttleName' when calling updateLogLogshuttle");
      }

      let pathParams = {
        'service_id': serviceId,
        'version_id': versionId,
        'logging_logshuttle_name': loggingLogshuttleName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'created_at': opts['createdAt'],
        'deleted_at': opts['deletedAt'],
        'updated_at': opts['updatedAt'],
        'service_id': opts['serviceId2'],
        'version': opts['version'],
        'name': opts['name'],
        'placement': opts['placement'],
        'format_version': opts['formatVersion'],
        'response_condition': opts['responseCondition'],
        'format': opts['format'],
        'token': opts['token'],
        'url': opts['url']
      };

      let authNames = ['token_engineer'];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = InlineObject1;
      return this.apiClient.callApi(
        '/service/{service_id}/version/{version_id}/logging/logshuttle/{logging_logshuttle_name}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    updateLogLogshuttle(serviceId, versionId, loggingLogshuttleName, opts) {
      return this.updateLogLogshuttleWithHttpInfo(serviceId, versionId, loggingLogshuttleName, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
