/**
 * Billing address
 * A billing address is used to calculate your bill correctly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillingAddress);
  }
}(this, function(expect, BillingAddress) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BillingAddress.AccountBillingAddressApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccountBillingAddressApi', function() {
    describe('addBillingAddr', function() {
      it('should call addBillingAddr successfully', function(done) {
        //uncomment below and update the code to test addBillingAddr
        //instance.addBillingAddr(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBillingAddr', function() {
      it('should call deleteBillingAddr successfully', function(done) {
        //uncomment below and update the code to test deleteBillingAddr
        //instance.deleteBillingAddr(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBillingAddr', function() {
      it('should call getBillingAddr successfully', function(done) {
        //uncomment below and update the code to test getBillingAddr
        //instance.getBillingAddr(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateBillingAddr', function() {
      it('should call updateBillingAddr successfully', function(done) {
        //uncomment below and update the code to test updateBillingAddr
        //instance.updateBillingAddr(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
