/**
 * Dictionary info
 * Dictionary Info is a set of metadata describing properties of a dictionary which change as items are added and removed.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import InlineResponse200 from './model/InlineResponse200';
import ModelDictionaryInfo from './model/ModelDictionaryInfo';
import DictionariesDictionaryInfoApi from './api/DictionariesDictionaryInfoApi';



export {
    
    ApiClient,

    
    InlineResponse200,

    
    ModelDictionaryInfo,

    
    DictionariesDictionaryInfoApi
};
