/**
 * Customer
 * A Customer is the base object that owns your Users and Services.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class RelationshipCustomerCustomerData {
    
    constructor() { 
        
        RelationshipCustomerCustomerData.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RelationshipCustomerCustomerData();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}


RelationshipCustomerCustomerData.prototype['type'] = undefined;


RelationshipCustomerCustomerData.prototype['id'] = undefined;






export default RelationshipCustomerCustomerData;

