/**
 * HTTPS
 * Fastly will upload log messages to an HTTPS endpoint in the format specified in the HTTPS object. The HTTPS endpoint requires proof of domain ownership before logs can be received. Learn how to validate your domain in our [HTTPS endpoint documentation](https://docs.fastly.com/en/guides/log-streaming-https).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class InlineObject {
    
    constructor() { 
        
        InlineObject.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('service_id')) {
                obj['service_id'] = ApiClient.convertToType(data['service_id'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('placement')) {
                obj['placement'] = ApiClient.convertToType(data['placement'], 'String');
            }
            if (data.hasOwnProperty('format_version')) {
                obj['format_version'] = ApiClient.convertToType(data['format_version'], 'Number');
            }
            if (data.hasOwnProperty('response_condition')) {
                obj['response_condition'] = ApiClient.convertToType(data['response_condition'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('tls_ca_cert')) {
                obj['tls_ca_cert'] = ApiClient.convertToType(data['tls_ca_cert'], 'String');
            }
            if (data.hasOwnProperty('tls_client_cert')) {
                obj['tls_client_cert'] = ApiClient.convertToType(data['tls_client_cert'], 'String');
            }
            if (data.hasOwnProperty('tls_client_key')) {
                obj['tls_client_key'] = ApiClient.convertToType(data['tls_client_key'], 'String');
            }
            if (data.hasOwnProperty('tls_hostname')) {
                obj['tls_hostname'] = ApiClient.convertToType(data['tls_hostname'], 'String');
            }
            if (data.hasOwnProperty('request_max_entries')) {
                obj['request_max_entries'] = ApiClient.convertToType(data['request_max_entries'], 'Number');
            }
            if (data.hasOwnProperty('request_max_bytes')) {
                obj['request_max_bytes'] = ApiClient.convertToType(data['request_max_bytes'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
            if (data.hasOwnProperty('header_name')) {
                obj['header_name'] = ApiClient.convertToType(data['header_name'], 'String');
            }
            if (data.hasOwnProperty('message_type')) {
                obj['message_type'] = ApiClient.convertToType(data['message_type'], 'String');
            }
            if (data.hasOwnProperty('header_value')) {
                obj['header_value'] = ApiClient.convertToType(data['header_value'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('json_format')) {
                obj['json_format'] = ApiClient.convertToType(data['json_format'], 'String');
            }
        }
        return obj;
    }


}


InlineObject.prototype['created_at'] = undefined;


InlineObject.prototype['deleted_at'] = undefined;


InlineObject.prototype['updated_at'] = undefined;


InlineObject.prototype['service_id'] = undefined;


InlineObject.prototype['version'] = undefined;


InlineObject.prototype['name'] = undefined;


InlineObject.prototype['placement'] = undefined;


InlineObject.prototype['format_version'] = FormatVersionEnum.2;


InlineObject.prototype['response_condition'] = undefined;


InlineObject.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';


InlineObject.prototype['tls_ca_cert'] = 'null';


InlineObject.prototype['tls_client_cert'] = 'null';


InlineObject.prototype['tls_client_key'] = 'null';


InlineObject.prototype['tls_hostname'] = 'null';


InlineObject.prototype['request_max_entries'] = 0;


InlineObject.prototype['request_max_bytes'] = 0;


InlineObject.prototype['url'] = undefined;


InlineObject.prototype['content_type'] = 'null';


InlineObject.prototype['header_name'] = 'null';


InlineObject.prototype['message_type'] = 'classic';


InlineObject.prototype['header_value'] = 'null';


InlineObject.prototype['method'] = 'POST';


InlineObject.prototype['json_format'] = undefined;






InlineObject['PlacementEnum'] = {

    
    "none": "none",

    
    "waf_debug": "waf_debug",

    
    "null": "null"
};



InlineObject['FormatVersionEnum'] = {

    
    "1": 1,

    
    "2": 2
};



InlineObject['MessageTypeEnum'] = {

    
    "classic": "classic",

    
    "loggly": "loggly",

    
    "logplex": "logplex",

    
    "blank": "blank"
};



InlineObject['MethodEnum'] = {

    
    "POST": "POST",

    
    "PUT": "PUT"
};



InlineObject['JsonFormatEnum'] = {

    
    "0": "0",

    
    "1": "1",

    
    "2": "2"
};



export default InlineObject;

