/**
 * Fastly API
 * Via the Fastly API you can perform any of the operations that are possible within the management console,  including creating services, domains, and backends, configuring rules or uploading your own application code, as well as account operations such as user administration and billing reports. The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts. For the most accurate and up-to-date API reference content, visit our [Developer Hub](https://developer.fastly.com/reference/api/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DictionaryResponse from '../model/DictionaryResponse';


export default class DictionaryApi {

    
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    createDictionaryWithHttpInfo(service_id, version_id, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'service_id' is set
      if (service_id === undefined || service_id === null) {
        throw new Error("Missing the required parameter 'service_id' when calling createDictionary");
      }
      // verify the required parameter 'version_id' is set
      if (version_id === undefined || version_id === null) {
        throw new Error("Missing the required parameter 'version_id' when calling createDictionary");
      }

      let pathParams = {
        'service_id': service_id,
        'version_id': version_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': opts['name'],
        'write_only': opts['write_only']
      };

      let authNames = ['token'];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = DictionaryResponse;
      return this.apiClient.callApi(
        '/service/{service_id}/version/{version_id}/dictionary', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    createDictionary(service_id, version_id, opts) {
      return this.createDictionaryWithHttpInfo(service_id, version_id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    deleteDictionaryWithHttpInfo(service_id, version_id, dictionary_name) {
      let postBody = null;
      // verify the required parameter 'service_id' is set
      if (service_id === undefined || service_id === null) {
        throw new Error("Missing the required parameter 'service_id' when calling deleteDictionary");
      }
      // verify the required parameter 'version_id' is set
      if (version_id === undefined || version_id === null) {
        throw new Error("Missing the required parameter 'version_id' when calling deleteDictionary");
      }
      // verify the required parameter 'dictionary_name' is set
      if (dictionary_name === undefined || dictionary_name === null) {
        throw new Error("Missing the required parameter 'dictionary_name' when calling deleteDictionary");
      }

      let pathParams = {
        'service_id': service_id,
        'version_id': version_id,
        'dictionary_name': dictionary_name
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/service/{service_id}/version/{version_id}/dictionary/{dictionary_name}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    deleteDictionary(service_id, version_id, dictionary_name) {
      return this.deleteDictionaryWithHttpInfo(service_id, version_id, dictionary_name)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    getDictionaryWithHttpInfo(service_id, version_id, dictionary_name) {
      let postBody = null;
      // verify the required parameter 'service_id' is set
      if (service_id === undefined || service_id === null) {
        throw new Error("Missing the required parameter 'service_id' when calling getDictionary");
      }
      // verify the required parameter 'version_id' is set
      if (version_id === undefined || version_id === null) {
        throw new Error("Missing the required parameter 'version_id' when calling getDictionary");
      }
      // verify the required parameter 'dictionary_name' is set
      if (dictionary_name === undefined || dictionary_name === null) {
        throw new Error("Missing the required parameter 'dictionary_name' when calling getDictionary");
      }

      let pathParams = {
        'service_id': service_id,
        'version_id': version_id,
        'dictionary_name': dictionary_name
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DictionaryResponse;
      return this.apiClient.callApi(
        '/service/{service_id}/version/{version_id}/dictionary/{dictionary_name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    getDictionary(service_id, version_id, dictionary_name) {
      return this.getDictionaryWithHttpInfo(service_id, version_id, dictionary_name)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    listDictionariesWithHttpInfo(service_id, version_id) {
      let postBody = null;
      // verify the required parameter 'service_id' is set
      if (service_id === undefined || service_id === null) {
        throw new Error("Missing the required parameter 'service_id' when calling listDictionaries");
      }
      // verify the required parameter 'version_id' is set
      if (version_id === undefined || version_id === null) {
        throw new Error("Missing the required parameter 'version_id' when calling listDictionaries");
      }

      let pathParams = {
        'service_id': service_id,
        'version_id': version_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [DictionaryResponse];
      return this.apiClient.callApi(
        '/service/{service_id}/version/{version_id}/dictionary', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    listDictionaries(service_id, version_id) {
      return this.listDictionariesWithHttpInfo(service_id, version_id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    updateDictionaryWithHttpInfo(service_id, version_id, dictionary_name, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'service_id' is set
      if (service_id === undefined || service_id === null) {
        throw new Error("Missing the required parameter 'service_id' when calling updateDictionary");
      }
      // verify the required parameter 'version_id' is set
      if (version_id === undefined || version_id === null) {
        throw new Error("Missing the required parameter 'version_id' when calling updateDictionary");
      }
      // verify the required parameter 'dictionary_name' is set
      if (dictionary_name === undefined || dictionary_name === null) {
        throw new Error("Missing the required parameter 'dictionary_name' when calling updateDictionary");
      }

      let pathParams = {
        'service_id': service_id,
        'version_id': version_id,
        'dictionary_name': dictionary_name
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': opts['name'],
        'write_only': opts['write_only']
      };

      let authNames = ['token'];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = DictionaryResponse;
      return this.apiClient.callApi(
        '/service/{service_id}/version/{version_id}/dictionary/{dictionary_name}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    updateDictionary(service_id, version_id, dictionary_name, opts) {
      return this.updateDictionaryWithHttpInfo(service_id, version_id, dictionary_name, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
