/**
 * Fastly API
 * Via the Fastly API you can perform any of the operations that are possible within the management console,  including creating services, domains, and backends, configuring rules or uploading your own application code, as well as account operations such as user administration and billing reports. The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts. For the most accurate and up-to-date API reference content, visit developer.fastly.com/reference/api/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";


export default class TlsBulkCertificatesApi {

    
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    deleteBulkTlsCertWithHttpInfo(certificate_id) {
      let postBody = null;
      // verify the required parameter 'certificate_id' is set
      if (certificate_id === undefined || certificate_id === null) {
        throw new Error("Missing the required parameter 'certificate_id' when calling deleteBulkTlsCert");
      }

      let pathParams = {
        'certificate_id': certificate_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/tls/bulk/certificates/{certificate_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    deleteBulkTlsCert(certificate_id) {
      return this.deleteBulkTlsCertWithHttpInfo(certificate_id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    getTlsBulkCertWithHttpInfo(certificate_id) {
      let postBody = null;
      // verify the required parameter 'certificate_id' is set
      if (certificate_id === undefined || certificate_id === null) {
        throw new Error("Missing the required parameter 'certificate_id' when calling getTlsBulkCert");
      }

      let pathParams = {
        'certificate_id': certificate_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/vnd.api+json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/tls/bulk/certificates/{certificate_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    getTlsBulkCert(certificate_id) {
      return this.getTlsBulkCertWithHttpInfo(certificate_id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    listTlsBulkCertsWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'filter[tls_domain.id][match]': opts['filter_tls_domain_id_match'],
        'page[number]': opts['page_number'],
        'page[size]': opts['page_size'],
        'sort': opts['sort']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = [];
      let accepts = ['application/vnd.api+json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/tls/bulk/certificates', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    listTlsBulkCerts(opts) {
      return this.listTlsBulkCertsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    updateBulkTlsCertWithHttpInfo(certificate_id, opts) {
      opts = opts || {};
      let postBody = opts['body'];
      // verify the required parameter 'certificate_id' is set
      if (certificate_id === undefined || certificate_id === null) {
        throw new Error("Missing the required parameter 'certificate_id' when calling updateBulkTlsCert");
      }

      let pathParams = {
        'certificate_id': certificate_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = ['application/vnd.api+json'];
      let accepts = ['application/vnd.api+json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/tls/bulk/certificates/{certificate_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    updateBulkTlsCert(certificate_id, opts) {
      return this.updateBulkTlsCertWithHttpInfo(certificate_id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
    uploadTlsBulkCertWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['token'];
      let contentTypes = ['application/vnd.api+json'];
      let accepts = ['application/vnd.api+json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/tls/bulk/certificates', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }
    uploadTlsBulkCert(opts) {
      return this.uploadTlsBulkCertWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
