/**
 * SFTP
 * Fastly will upload log messages periodically to the server in the format specified in the SFTP object.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class ModelLoggingSftp {
    
    constructor() { 
        
        ModelLoggingSftp.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelLoggingSftp();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('service_id')) {
                obj['service_id'] = ApiClient.convertToType(data['service_id'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('placement')) {
                obj['placement'] = ApiClient.convertToType(data['placement'], 'String');
            }
            if (data.hasOwnProperty('format_version')) {
                obj['format_version'] = ApiClient.convertToType(data['format_version'], 'Number');
            }
            if (data.hasOwnProperty('response_condition')) {
                obj['response_condition'] = ApiClient.convertToType(data['response_condition'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('message_type')) {
                obj['message_type'] = ApiClient.convertToType(data['message_type'], 'String');
            }
            if (data.hasOwnProperty('timestamp_format')) {
                obj['timestamp_format'] = ApiClient.convertToType(data['timestamp_format'], 'String');
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'Number');
            }
            if (data.hasOwnProperty('gzip_level')) {
                obj['gzip_level'] = ApiClient.convertToType(data['gzip_level'], 'Number');
            }
            if (data.hasOwnProperty('compression_codec')) {
                obj['compression_codec'] = ApiClient.convertToType(data['compression_codec'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('public_key')) {
                obj['public_key'] = ApiClient.convertToType(data['public_key'], 'String');
            }
            if (data.hasOwnProperty('secret_key')) {
                obj['secret_key'] = ApiClient.convertToType(data['secret_key'], 'String');
            }
            if (data.hasOwnProperty('ssh_known_hosts')) {
                obj['ssh_known_hosts'] = ApiClient.convertToType(data['ssh_known_hosts'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
        }
        return obj;
    }


}


ModelLoggingSftp.prototype['created_at'] = undefined;


ModelLoggingSftp.prototype['deleted_at'] = undefined;


ModelLoggingSftp.prototype['updated_at'] = undefined;


ModelLoggingSftp.prototype['service_id'] = undefined;


ModelLoggingSftp.prototype['version'] = undefined;


ModelLoggingSftp.prototype['name'] = undefined;


ModelLoggingSftp.prototype['placement'] = undefined;


ModelLoggingSftp.prototype['format_version'] = FormatVersionEnum.2;


ModelLoggingSftp.prototype['response_condition'] = undefined;


ModelLoggingSftp.prototype['format'] = '%h %l %u %t "%r" %&gt;s %b';


ModelLoggingSftp.prototype['message_type'] = 'classic';


ModelLoggingSftp.prototype['timestamp_format'] = undefined;


ModelLoggingSftp.prototype['period'] = 3600;


ModelLoggingSftp.prototype['gzip_level'] = 0;


ModelLoggingSftp.prototype['compression_codec'] = undefined;


ModelLoggingSftp.prototype['address'] = undefined;


ModelLoggingSftp.prototype['port'] = 22;


ModelLoggingSftp.prototype['password'] = undefined;


ModelLoggingSftp.prototype['path'] = 'null';


ModelLoggingSftp.prototype['public_key'] = 'null';


ModelLoggingSftp.prototype['secret_key'] = 'null';


ModelLoggingSftp.prototype['ssh_known_hosts'] = undefined;


ModelLoggingSftp.prototype['user'] = undefined;






ModelLoggingSftp['PlacementEnum'] = {

    
    "none": "none",

    
    "waf_debug": "waf_debug",

    
    "null": "null"
};



ModelLoggingSftp['FormatVersionEnum'] = {

    
    "1": 1,

    
    "2": 2
};



ModelLoggingSftp['MessageTypeEnum'] = {

    
    "classic": "classic",

    
    "loggly": "loggly",

    
    "logplex": "logplex",

    
    "blank": "blank"
};



ModelLoggingSftp['CompressionCodecEnum'] = {

    
    "zstd": "zstd",

    
    "snappy": "snappy",

    
    "gzip": "gzip"
};



export default ModelLoggingSftp;

