/**
 * Billing address
 * A billing address is used to calculate your bill correctly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse200DataRelationshipsCustomerData from './InlineResponse200DataRelationshipsCustomerData';


class InlineResponse200DataRelationshipsCustomer {
    
    constructor() { 
        
        InlineResponse200DataRelationshipsCustomer.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200DataRelationshipsCustomer();

            if (data.hasOwnProperty('data')) {
                obj['data'] = InlineResponse200DataRelationshipsCustomerData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}


InlineResponse200DataRelationshipsCustomer.prototype['data'] = undefined;






export default InlineResponse200DataRelationshipsCustomer;

