/**
 * Billing address
 * A billing address is used to calculate your bill correctly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse200DataRelationshipsCustomer from './InlineResponse200DataRelationshipsCustomer';


class InlineResponse200DataRelationships {
    
    constructor() { 
        
        InlineResponse200DataRelationships.initialize(this);
    }

    
    static initialize(obj) { 
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200DataRelationships();

            if (data.hasOwnProperty('customer')) {
                obj['customer'] = InlineResponse200DataRelationshipsCustomer.constructFromObject(data['customer']);
            }
        }
        return obj;
    }


}


InlineResponse200DataRelationships.prototype['customer'] = undefined;






export default InlineResponse200DataRelationships;

