name: Release CI
on:
  push:
    tags:
      - 'release/v?[0-9]*'

env:
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: main
      - name: Set up environment variables
        run: ./.github/scripts/publish_env.sh >> $GITHUB_ENV
        working-directory: ./main
        shell: bash
      - name: Pack API client
        run: ./.github/scripts/pack.sh
        working-directory: ./main
        shell: bash
      - name: Auth with NPM
        run: npm config set "//registry.npmjs.org/:_authToken" "${{ secrets.NPM_PUBLISH_TOKEN }}"
      - name: Publish API client
        run: ./.github/scripts/publish.sh
        working-directory: ./main
        shell: bash
      - name: Write release body file
        run: API_CLIENT_NAME=JavaScript CODE_PATH=./main ./main/.github/scripts/release_body.sh > ./dist/release_body.txt
        shell: bash
      - name: Create release (dry run)
        if: ${{ env.DRY_RUN == '1' }}
        run: cat ./dist/release_body.txt
      - name: Create GitHub release
        if: ${{ env.DRY_RUN != '1' }}
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ env.VERSION }}
          body_path: ./dist/release_body.txt
          files: |
            ./dist/${{ env.PACKAGE_FILENAME }}
          draft: false
          prerelease: ${{ env.PUBLISH_TAG != 'latest' }}
